local red='#ed8796'
local yellow='#eed49f'
local blue='#8aadf4'
local magenta='#c6a0f6'
local cyan='#8bd5ca'
local white='#cad3f5'
local green='#a6da95'

SPACESHIP_PROMPT_DEFAULT_PREFIX=" "

SPACESHIP_DIR_COLOR=$blue
SPACESHIP_EXEC_TIME_COLOR=$yellow
SPACESHIP_GIT_STATUS_COLOR=$red
SPACESHIP_GIT_BRANCH_COLOR=$magenta
SPACESHIP_CHAR_COLOR_SUCCESS=$green
SPACESHIP_CHAR_COLOR_FAILURE=$red
SPACESHIP_CHAR_COLOR_SECONDARY=$yellow

SPACESHIP_NODE_COLOR=$green
SPACESHIP_NODE_SYMBOL=' '
SPACESHIP_PYTHON_COLOR=$yellow
SPACESHIP_VENV_COLOR=$cyan
SPACESHIP_LUA_COLOR=$cyan

SPACESHIP_GIT_PREFIX=""

SPACESHIP_PACKAGE_SHOW=false
